name: Extended Metadata Sync

on:
  schedule:
     - cron: '50 * * * *'
  push:
    branches:
      - main
    paths:
      - .trigger

jobs:

  sync:
    name: Sync Extended Metadata
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: DanTup/gh-actions/setup-dart@v1.1.0

      - working-directory: scripts
        run: pub get

      - working-directory: scripts
        run: dart bin/download_metadata.dart --extended-only
        env:
          BLOCKFROST_API_KEY: ${{ secrets.BLOCKFROST_API_KEY }}

      - working-directory: data
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Update extended metadata" || true
          git push origin

  notify_failure:
    name: Notify Chat of Failure
    needs: sync
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Chat
        run: |
          curl --header "Content-Type: application/json" \
          --request POST \
          --data "{\"text\": \"<users/all>: Build failure! $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID \"}" \
          $CHAT_WEBHOOK_URL
        env:
          CHAT_WEBHOOK_URL: ${{ secrets.ALERT_CHAT_WEBHOOK_URL }}
